### ISSUE TITLE
[Request] Replace Vanilla Mob spawns with Brawlator spawns

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Brawlator#3]
When enabled default (and modded) mob spawns will be replaced with Brawlator mobs identified by the Brawlator name variable from monsters.conf

```
mobOverride=[
     minecraft:creeper="Megaboomer"
     minecraft:skeleton="Tank Archer"
     minecraft:zombie="Humanity Leftover"
     minecraft:pig="Mister Pig"
     mocreatures:rabbit="Holy Grail"
]

**Comment by zessirb** [comment]
Spook has added an additionnal "naturalSpawn" clause in the monster config, it is possible that it might at least partially suit your needs.  
It would looks like this :
```
naturalSpawn={
            probability = 1d
            biomeType = "minecraft:forest"
            maxHeight = 30
        }
```
It would be more like adding potential spawn than replacing it, though.

@Hbeau Could you give us more info ?

**Comment by Hbeau** [comment]
Exactly, you can set in which biome and/or at which height your override entity will spawn

**Comment by zessirb** [comment]
Cool, what does the probability "1d" mean?

**Comment by Hbeau** [comment]
d stand for double

**Comment by zessirb** [comment]
Ok I mentioned that part in the README.  
This should match your need, hellbringer, but it requires you to set it for every biome you need (included a [link to possible biomes](https://minecraft.gamepedia.com/Biome/ID) in the README, only look for the java edition ones)  
A probability of 1d will replace every spawn matching the other criterias.
