### ISSUE TITLE
[Request] Definable equipment

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Brawlator#4]
Add the ability to define equipment within the mob config.
Example
```bash
    {
        damage=1.0
        hp=5.0
        knockbackResistance=1
        name="Humanity leftover"
        speed=1.0
        type=zombie
        equipment={
          head: {ref : "ItemizerHelm"}
          mainhand: {pool_ref : 1}
          legs: {name: "minecraft:leather_leggings"}
          
        }
    }
```

**Comment by zessirb** [comment]
Hello, it looks like it has been at least partially implemented. [It is in the last release](https://github.com/OnapleRPG/Brawlator/releases/download/1.2.0/Brawlator-1.2.0.jar).  

Here is an exemple: 
`monsters=[
    {
        damage=1.0
        hp=50.0
        knockbackResistance=1
        name="Sandstorm Crusader"
        speed=1.0
        type=skeleton,
        pools=["table1","table3"]
        equipments = {
            offHand : {name : "bow"}
            mainHand : {name : "golden_axe"}
            head : {name : "golden_helmet"}
            chest : {name : "leather_chestplate"}
            legs : {name : "diamond_leggings"}
            foot : {name : "iron_boots"}
        }
    }
]`
This is now in the default config, and it spawns a scary skeleton with armor.

If you want to use Itemizer items, you can replace `name: golden_axe` with `ref: barbarian_axe` for instance.  
Pools have not been implemented for now. 
I'm closing the issue for the definable equipment, you can open a new one if you want the pool fetching to be possible too
