### ISSUE TITLE
Allow natural spawn override for all biomes

### ISSUE THREAD

**Issue by zessirb** [OnapleRPG/Brawlator#8]
Natural spawn override should work when no biome is specified. It would then override the spawn for all biomes, but biome specific overrides would keep priorities over it.
config-wise, we could simply act that no biome = all biome 
*(related to #7)*

**Comment by SirFancyBacon** [comment]
Found out my issue was a config error and that this already functions correctly.

Sorry!!

**Comment by zessirb** [comment]
Np! Closing the issue since already implemented
